// Produtos da Barba Lenhador — 93 links Yampi
// Para adicionar: { nome: '...', link_yampi: 'https://...', categoria: '...' }

const PRODUCTS = [
  { nome: "1 Ativador + 1 Multivitaminico",                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/GK3PYAKHRQ",  categoria: "Kit" },
  { nome: "1 Ativador de crescimento",                                                  link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/D8JNCVTSPQ",  categoria: "Ativador" },
  { nome: "1 C/ Kirkland",                                                              link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/BUIGVACYA",   categoria: "Kirkland Caixa" },
  { nome: "1 C/ Kirkland + 1 Multivitaminico",                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/XXXZFPUXJG",  categoria: "Kirkland Caixa" },
  { nome: "1 C/ Kirkland + 1 Pente de Madeira + 1 Máquina de Acabamento + 1 Chapinha", link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/GXZK7WNNWA",  categoria: "Kit" },
  { nome: "1 C/ Kirkland + 3 Multivitaminicos + Derma Roller",                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/ANU0WHARNG",  categoria: "Kirkland Caixa" },
  { nome: "1 C/ Kirkland + Dermaroller",                                               link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/GYQJFXUNWA",  categoria: "Kirkland Caixa" },
  { nome: "1 C/ Kirkland + Dermaroller 394",                                           link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/NBADAGFH0G",  categoria: "Kirkland Caixa" },
  { nome: "1 C/ Kirkland + Pente de Madeira",                                          link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/O5OIQJYA",    categoria: "Kirkland Caixa" },
  { nome: "1 C/Kirkland + Hidratante",                                                 link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/6Z3GYVCFBW",  categoria: "Kirkland Caixa" },
  { nome: "1 Caixa de Minoxidil + 1 Multivitaminico + 1 Ativador",                    link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/GGVREWNZ6Q",  categoria: "Minoxidil Caixa" },
  { nome: "1 Caixa de Minoxidil + Dermaroller",                                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/JZJ2GSH7PQ",  categoria: "Minoxidil Caixa" },
  { nome: "1 Caixa Minoxidil + 1 Multivitamínico + Dermaroller",                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/VJ7SLWJ0A",   categoria: "Minoxidil Caixa" },
  { nome: "1 F/ Kirkland",                                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/Q2IOCENMWQ",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Hidratante Facial",                                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/OBWFBVMOGW",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Hidratante Facial + 1 Derma Roller",                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/CPKEYQVVOQ",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Hidratante Facial + 1 Esfoliante + 1 Multivitamínico",   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/DSK5QLTDBA",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Multivitaminico",                                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/FWCUXRXDW",   categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Multivitaminico + Derma Roller",                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/XWMWITPG8G",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Pomada efeito seco",                                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/HRYTRQGVVQ",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Pomada efeito seco + Derma Roller",                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/TWIOXQQIDA",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + 1 Pomada efeito úmido + Derma Roller",                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/QSKWKWTDTQ",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + Derma roller C/ Conta-gotas",                              link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/LSL8FYPDA",   categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland + Pomada efeito úmido",                                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/VQMUY9SSMW",  categoria: "Kirkland Frasco" },
  { nome: "1 F/ Kirkland s/ conta-gotas",                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/QG43WOJTIQ",  categoria: "Kirkland Frasco" },
  { nome: "1 Frasco + Espuma Massageadora",                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/OOYAJRM6W",   categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco 86,90",                                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/3MMEIXU08W",  categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco de Minoxidil + 1 Ativador de crescimento",                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/YM4TVBM7QA",  categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco Minox 109",                                                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/T5EGHLPHZG",  categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco Minoxidil + 1 Multivitamínico + 1 Pomada",                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/18BW6K6EA",   categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco Minoxidil + 1 Multivitaminico Ativador",                          link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/3EF9ROF1WA",  categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco Minoxidil + Dermaroller",                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/EYSZ7O0IQ",   categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco Minoxidil 89",                                                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/92SILHLQ2Q",  categoria: "Minoxidil Frasco" },
  { nome: "1 Frasco Minoxidil 94",                                                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/Y5GXDNXA",    categoria: "Minoxidil Frasco" },
  { nome: "1 Hidratante + 1 Espuma massageadora",                                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/MTOHO4D0W",   categoria: "Skincare" },
  { nome: "1 Kit lenhador + Dermaroller",                                              link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/U1JKSAH3W",   categoria: "Kit" },
  { nome: "1 Minoxidil + 1 Multivitamínico",                                          link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/ASASTUZPAQ",  categoria: "Minoxidil Frasco" },
  { nome: "1 Minoxidil Foligain exclusivo",                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/0TJS99UW",    categoria: "Foligain" },
  { nome: "1 Multivitaminico",                                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/ONO7XRBAPW",  categoria: "Multivitaminico" },
  { nome: "1 Pomada efeito Seco",                                                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/IAXI2LALYW",  categoria: "Pomada" },
  { nome: "1 Pomada Efeito Úmido",                                                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/QP0YMLY7Q",   categoria: "Pomada" },
  { nome: "10 Frascos de minoxidil",                                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/YP2NN9LAOW",  categoria: "Minoxidil Frasco" },
  { nome: "15 Frascos Minoxidil",                                                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/XIYEYRR62G",  categoria: "Minoxidil Frasco" },
  { nome: "2 Ativadores crescimento",                                                  link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/LFNNSDIAXQ",  categoria: "Ativador" },
  { nome: "2 C/ Kirkland",                                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/EJBU0F4SGW",  categoria: "Kirkland Caixa" },
  { nome: "2 F/ Kirkland",                                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/ACEZYT3ZOA",  categoria: "Kirkland Frasco" },
  { nome: "2 F/ Kirkland + 2 Multivitaminico",                                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/MI9I05ES3A",  categoria: "Kirkland Frasco" },
  { nome: "2 F/ Kirkland + Dermaroller",                                              link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/GDLNW8QYTG",  categoria: "Kirkland Frasco" },
  { nome: "2 F/ Kirkland S/ Conta-gotas",                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/B6AKVN5YQ",   categoria: "Kirkland Frasco" },
  { nome: "2 Frascos + Esfoliante",                                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/8MXS0KJ0QA",  categoria: "Minoxidil Frasco" },
  { nome: "2 Frascos de Minoxidil + 1 Multivitamínco + Dermaroller",                 link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/VZLKXNPP2W",  categoria: "Minoxidil Frasco" },
  { nome: "2 Frascos Foligain",                                                       link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/QISBJ4JV3Q",  categoria: "Foligain" },
  { nome: "2 Frascos Minoxidil + 2 Multivitamínico + Dermaroller",                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/FC1YFARFA",   categoria: "Minoxidil Frasco" },
  { nome: "2 Frascos Minoxidil FG",                                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/VAETQPK9W",   categoria: "Minoxidil Frasco" },
  { nome: "2 Multivitamínico Ativador MAJOR",                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/90QEHAKQEW",  categoria: "Multivitaminico" },
  { nome: "2 Pomadas efeito úmido",                                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/II8ADF7PUQ",  categoria: "Pomada" },
  { nome: "3 F/ Kirkland",                                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/NLTGOGOQWA",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland + 1 Multivitamínico",                                       link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/2MKW1CVZLG",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland + 1 Pomada Efeito Seco",                                    link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/7D1ANKITA",   categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland + 1 Pomada Efeito Úmido + 1 Derma roller",                 link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/SVBXMB9QG",   categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland + 3 Multivitaminicos",                                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/LZFEDZN4XG",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland + 3 Multivitaminicos + 2 Hidratantes",                      link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/C4CLUHHEDW",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland + Dermaroller",                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/VLPFDILRG",   categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland + Pente de madeiras",                                       link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/JR2XZQTNRQ",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland 2 conta-gotas",                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/ADEFNAIRMA",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland 219 FG",                                                    link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/MEYZSMIXZA",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland C/ Conta-Gotas + Dermaroller",                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/NAVJ1NMQFA",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland S/ Conta-Gotas",                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/BUOJCBFR9A",  categoria: "Kirkland Frasco" },
  { nome: "3 F/ Kirkland SEDEX",                                                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/KQCLN1UHBW",  categoria: "Kirkland Frasco" },
  { nome: "3 FRASCOS + 3 MULTIVITAMÍNICOS + 1 DERMA ROLLER",                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/OZPGYNM4YG",  categoria: "Minoxidil Frasco" },
  { nome: "3 Frascos + Dermaroller FG",                                              link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/OTCED63CAQ",  categoria: "Minoxidil Frasco" },
  { nome: "3 Frascos 219",                                                           link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/FYQW9QSSUA",  categoria: "Minoxidil Frasco" },
  { nome: "3 Frascos 244 FG",                                                        link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/OKGY2MAITA",  categoria: "Minoxidil Frasco" },
  { nome: "3 Frascos Minoxidil FG",                                                  link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/BGQIOUE26Q",  categoria: "Minoxidil Frasco" },
  { nome: "3 Frascos Minoxidil FG 229",                                              link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/I3XAY5QTHQ",  categoria: "Minoxidil Frasco" },
  { nome: "3 Frascos SEDEX",                                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/YFXEMAFGMW",  categoria: "Minoxidil Frasco" },
  { nome: "3 Multivitamínicos + 1 Esfoliante + 1 Hidratante + 1 Ativador tópico",  link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/PJJQGEYACG",  categoria: "Kit" },
  { nome: "4 Frascos de Minoxidil",                                                  link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/RWQH4ULQTG",  categoria: "Minoxidil Frasco" },
  { nome: "4 Frascos de Minoxidil + Dermaroller",                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/TMWXAXCPGW",  categoria: "Minoxidil Frasco" },
  { nome: "4 Frascos Minoxidil + 2 Ativadores",                                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/5YPZXUBQYW",  categoria: "Minoxidil Frasco" },
  { nome: "5 F/ Kirkland",                                                           link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/C8COVZGCZA",  categoria: "Kirkland Frasco" },
  { nome: "8 Frascos de Kirkland",                                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/0T4EWAKKDA",  categoria: "Kirkland Frasco" },
  { nome: "9 F/ Kirkland + Dermaroller",                                             link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/CQNBNX1TTA",  categoria: "Kirkland Frasco" },
  { nome: "C/ Kirkland 429",                                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/XJY1QQSNNG",  categoria: "Kirkland Caixa" },
  { nome: "Caixa 409,90",                                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/XCGCXJM5BW",  categoria: "Minoxidil Caixa" },
  { nome: "Caixa Minox 414",                                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/VMAWTUOCAA",  categoria: "Minoxidil Caixa" },
  { nome: "Caixa Minoxidil + 1 Dermaroller + Pente de madeira",                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/EVSOY1OMAW",  categoria: "Minoxidil Caixa" },
  { nome: "Derma roller",                                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/UCB8ZEKIAA",  categoria: "Acessório" },
  { nome: "Kit duo pomadas",                                                         link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/9GXLOSZO6G",  categoria: "Kit" },
  { nome: "Kit Lenhador",                                                            link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/ACDUG1SAJG",  categoria: "Kit" },
  { nome: "Kit lenhador + Dermaroller",                                              link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/0ZBE2RWUG",   categoria: "Kit" },
  { nome: "Kit Lenhador + Pomada efeito úmido",                                     link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/DJPR0HMVA",   categoria: "Kit" },
  { nome: "Kit Premium + Minoxidil",                                                 link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/ZD6KGHVU5W",  categoria: "Kit" },
  { nome: "Máquina de acabamento",                                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/SWOZWUP6SW",  categoria: "Acessório" },
  { nome: "2 Frascos Brasil",                                                   link_yampi: "https://seguro.loja-barbalenhador.com.br/pay/YDRONZYOA",  categoria: "campanha" },
];
