-- Inserir os 93 produtos na tabela produtos
-- Cole no SQL Editor do Supabase e execute

insert into produtos (nome, link_yampi, categoria, ativo) values
  ('1 Ativador + 1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/GK3PYAKHRQ', 'Kit', true),
  ('1 Ativador de crescimento', 'https://seguro.loja-barbalenhador.com.br/pay/D8JNCVTSPQ', 'Ativador', true),
  ('1 C/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/BUIGVACYA', 'Kirkland Caixa', true),
  ('1 C/ Kirkland + 1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/XXXZFPUXJG', 'Kirkland Caixa', true),
  ('1 C/ Kirkland + 1 Pente de Madeira + 1 Máquina de Acabamento + 1 Chapinha', 'https://seguro.loja-barbalenhador.com.br/pay/GXZK7WNNWA', 'Kit', true),
  ('1 C/ Kirkland + 3 Multivitaminicos + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/ANU0WHARNG', 'Kirkland Caixa', true),
  ('1 C/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/GYQJFXUNWA', 'Kirkland Caixa', true),
  ('1 C/ Kirkland + Dermaroller 394', 'https://seguro.loja-barbalenhador.com.br/pay/NBADAGFH0G', 'Kirkland Caixa', true),
  ('1 C/ Kirkland + Pente de Madeira', 'https://seguro.loja-barbalenhador.com.br/pay/O5OIQJYA', 'Kirkland Caixa', true),
  ('1 C/Kirkland + Hidratante', 'https://seguro.loja-barbalenhador.com.br/pay/6Z3GYVCFBW', 'Kirkland Caixa', true),
  ('1 Caixa de Minoxidil + 1 Multivitaminico + 1 Ativador', 'https://seguro.loja-barbalenhador.com.br/pay/GGVREWNZ6Q', 'Minoxidil Caixa', true),
  ('1 Caixa de Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/JZJ2GSH7PQ', 'Minoxidil Caixa', true),
  ('1 Caixa Minoxidil + 1 Multivitamínico + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/VJ7SLWJ0A', 'Minoxidil Caixa', true),
  ('1 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/Q2IOCENMWQ', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Hidratante Facial', 'https://seguro.loja-barbalenhador.com.br/pay/OBWFBVMOGW', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Hidratante Facial + 1 Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/CPKEYQVVOQ', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Hidratante Facial + 1 Esfoliante + 1 Multivitamínico', 'https://seguro.loja-barbalenhador.com.br/pay/DSK5QLTDBA', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/FWCUXRXDW', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Multivitaminico + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/XWMWITPG8G', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Pomada efeito seco', 'https://seguro.loja-barbalenhador.com.br/pay/HRYTRQGVVQ', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Pomada efeito seco + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/TWIOXQQIDA', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + 1 Pomada efeito úmido + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/QSKWKWTDTQ', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + Derma roller C/ Conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/LSL8FYPDA', 'Kirkland Frasco', true),
  ('1 F/ Kirkland + Pomada efeito úmido', 'https://seguro.loja-barbalenhador.com.br/pay/VQMUY9SSMW', 'Kirkland Frasco', true),
  ('1 F/ Kirkland s/ conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/QG43WOJTIQ', 'Kirkland Frasco', true),
  ('1 Frasco + Espuma Massageadora', 'https://seguro.loja-barbalenhador.com.br/pay/OOYAJRM6W', 'Minoxidil Frasco', true),
  ('1 Frasco 86,90', 'https://seguro.loja-barbalenhador.com.br/pay/3MMEIXU08W', 'Minoxidil Frasco', true),
  ('1 Frasco de Minoxidil + 1 Ativador de crescimento', 'https://seguro.loja-barbalenhador.com.br/pay/YM4TVBM7QA', 'Minoxidil Frasco', true),
  ('1 Frasco Minox 109', 'https://seguro.loja-barbalenhador.com.br/pay/T5EGHLPHZG', 'Minoxidil Frasco', true),
  ('1 Frasco Minoxidil + 1 Multivitamínico + 1 Pomada', 'https://seguro.loja-barbalenhador.com.br/pay/18BW6K6EA', 'Minoxidil Frasco', true),
  ('1 Frasco Minoxidil + 1 Multivitaminico Ativador', 'https://seguro.loja-barbalenhador.com.br/pay/3EF9ROF1WA', 'Minoxidil Frasco', true),
  ('1 Frasco Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/EYSZ7O0IQ', 'Minoxidil Frasco', true),
  ('1 Frasco Minoxidil 89', 'https://seguro.loja-barbalenhador.com.br/pay/92SILHLQ2Q', 'Minoxidil Frasco', true),
  ('1 Frasco Minoxidil 94', 'https://seguro.loja-barbalenhador.com.br/pay/Y5GXDNXA', 'Minoxidil Frasco', true),
  ('1 Hidratante + 1 Espuma massageadora', 'https://seguro.loja-barbalenhador.com.br/pay/MTOHO4D0W', 'Skincare', true),
  ('1 Kit lenhador + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/U1JKSAH3W', 'Kit', true),
  ('1 Minoxidil + 1 Multivitamínico', 'https://seguro.loja-barbalenhador.com.br/pay/ASASTUZPAQ', 'Minoxidil Frasco', true),
  ('1 Minoxidil Foligain exclusivo', 'https://seguro.loja-barbalenhador.com.br/pay/0TJS99UW', 'Foligain', true),
  ('1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/ONO7XRBAPW', 'Multivitaminico', true),
  ('1 Pomada efeito Seco', 'https://seguro.loja-barbalenhador.com.br/pay/IAXI2LALYW', 'Pomada', true),
  ('1 Pomada Efeito Úmido', 'https://seguro.loja-barbalenhador.com.br/pay/QP0YMLY7Q', 'Pomada', true),
  ('10 Frascos de minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/YP2NN9LAOW', 'Minoxidil Frasco', true),
  ('15 Frascos Minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/XIYEYRR62G', 'Minoxidil Frasco', true),
  ('2 Ativadores crescimento', 'https://seguro.loja-barbalenhador.com.br/pay/LFNNSDIAXQ', 'Ativador', true),
  ('2 C/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/EJBU0F4SGW', 'Kirkland Caixa', true),
  ('2 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/ACEZYT3ZOA', 'Kirkland Frasco', true),
  ('2 F/ Kirkland + 2 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/MI9I05ES3A', 'Kirkland Frasco', true),
  ('2 F/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/GDLNW8QYTG', 'Kirkland Frasco', true),
  ('2 F/ Kirkland S/ Conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/B6AKVN5YQ', 'Kirkland Frasco', true),
  ('2 Frascos + Esfoliante', 'https://seguro.loja-barbalenhador.com.br/pay/8MXS0KJ0QA', 'Minoxidil Frasco', true),
  ('2 Frascos de Minoxidil + 1 Multivitamínco + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/VZLKXNPP2W', 'Minoxidil Frasco', true),
  ('2 Frascos Foligain', 'https://seguro.loja-barbalenhador.com.br/pay/QISBJ4JV3Q', 'Foligain', true),
  ('2 Frascos Minoxidil + 2 Multivitamínico + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/FC1YFARFA', 'Minoxidil Frasco', true),
  ('2 Frascos Minoxidil FG', 'https://seguro.loja-barbalenhador.com.br/pay/VAETQPK9W', 'Minoxidil Frasco', true),
  ('2 Multivitamínico Ativador MAJOR', 'https://seguro.loja-barbalenhador.com.br/pay/90QEHAKQEW', 'Multivitaminico', true),
  ('2 Pomadas efeito úmido', 'https://seguro.loja-barbalenhador.com.br/pay/II8ADF7PUQ', 'Pomada', true),
  ('3 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/NLTGOGOQWA', 'Kirkland Frasco', true),
  ('3 F/ Kirkland + 1 Multivitamínico', 'https://seguro.loja-barbalenhador.com.br/pay/2MKW1CVZLG', 'Kirkland Frasco', true),
  ('3 F/ Kirkland + 1 Pomada Efeito Seco', 'https://seguro.loja-barbalenhador.com.br/pay/7D1ANKITA', 'Kirkland Frasco', true),
  ('3 F/ Kirkland + 1 Pomada Efeito Úmido + 1 Derma roller', 'https://seguro.loja-barbalenhador.com.br/pay/SVBXMB9QG', 'Kirkland Frasco', true),
  ('3 F/ Kirkland + 3 Multivitaminicos', 'https://seguro.loja-barbalenhador.com.br/pay/LZFEDZN4XG', 'Kirkland Frasco', true),
  ('3 F/ Kirkland + 3 Multivitaminicos + 2 Hidratantes', 'https://seguro.loja-barbalenhador.com.br/pay/C4CLUHHEDW', 'Kirkland Frasco', true),
  ('3 F/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/VLPFDILRG', 'Kirkland Frasco', true),
  ('3 F/ Kirkland + Pente de madeiras', 'https://seguro.loja-barbalenhador.com.br/pay/JR2XZQTNRQ', 'Kirkland Frasco', true),
  ('3 F/ Kirkland 2 conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/ADEFNAIRMA', 'Kirkland Frasco', true),
  ('3 F/ Kirkland 219 FG', 'https://seguro.loja-barbalenhador.com.br/pay/MEYZSMIXZA', 'Kirkland Frasco', true),
  ('3 F/ Kirkland C/ Conta-Gotas + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/NAVJ1NMQFA', 'Kirkland Frasco', true),
  ('3 F/ Kirkland S/ Conta-Gotas', 'https://seguro.loja-barbalenhador.com.br/pay/BUOJCBFR9A', 'Kirkland Frasco', true),
  ('3 F/ Kirkland SEDEX', 'https://seguro.loja-barbalenhador.com.br/pay/KQCLN1UHBW', 'Kirkland Frasco', true),
  ('3 FRASCOS + 3 MULTIVITAMÍNICOS + 1 DERMA ROLLER', 'https://seguro.loja-barbalenhador.com.br/pay/OZPGYNM4YG', 'Minoxidil Frasco', true),
  ('3 Frascos + Dermaroller FG', 'https://seguro.loja-barbalenhador.com.br/pay/OTCED63CAQ', 'Minoxidil Frasco', true),
  ('3 Frascos 219', 'https://seguro.loja-barbalenhador.com.br/pay/FYQW9QSSUA', 'Minoxidil Frasco', true),
  ('3 Frascos 244 FG', 'https://seguro.loja-barbalenhador.com.br/pay/OKGY2MAITA', 'Minoxidil Frasco', true),
  ('3 Frascos Minoxidil FG', 'https://seguro.loja-barbalenhador.com.br/pay/BGQIOUE26Q', 'Minoxidil Frasco', true),
  ('3 Frascos Minoxidil FG 229', 'https://seguro.loja-barbalenhador.com.br/pay/I3XAY5QTHQ', 'Minoxidil Frasco', true),
  ('3 Frascos SEDEX', 'https://seguro.loja-barbalenhador.com.br/pay/YFXEMAFGMW', 'Minoxidil Frasco', true),
  ('3 Multivitamínicos + 1 Esfoliante + 1 Hidratante + 1 Ativador tópico', 'https://seguro.loja-barbalenhador.com.br/pay/PJJQGEYACG', 'Kit', true),
  ('4 Frascos de Minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/RWQH4ULQTG', 'Minoxidil Frasco', true),
  ('4 Frascos de Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/TMWXAXCPGW', 'Minoxidil Frasco', true),
  ('4 Frascos Minoxidil + 2 Ativadores', 'https://seguro.loja-barbalenhador.com.br/pay/5YPZXUBQYW', 'Minoxidil Frasco', true),
  ('5 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/C8COVZGCZA', 'Kirkland Frasco', true),
  ('8 Frascos de Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/0T4EWAKKDA', 'Kirkland Frasco', true),
  ('9 F/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/CQNBNX1TTA', 'Kirkland Frasco', true),
  ('C/ Kirkland 429', 'https://seguro.loja-barbalenhador.com.br/pay/XJY1QQSNNG', 'Kirkland Caixa', true),
  ('Caixa 409,90', 'https://seguro.loja-barbalenhador.com.br/pay/XCGCXJM5BW', 'Minoxidil Caixa', true),
  ('Caixa Minox 414', 'https://seguro.loja-barbalenhador.com.br/pay/VMAWTUOCAA', 'Minoxidil Caixa', true),
  ('Caixa Minoxidil + 1 Dermaroller + Pente de madeira', 'https://seguro.loja-barbalenhador.com.br/pay/EVSOY1OMAW', 'Minoxidil Caixa', true),
  ('Derma roller', 'https://seguro.loja-barbalenhador.com.br/pay/UCB8ZEKIAA', 'Acessório', true),
  ('Kit duo pomadas', 'https://seguro.loja-barbalenhador.com.br/pay/9GXLOSZO6G', 'Kit', true),
  ('Kit Lenhador', 'https://seguro.loja-barbalenhador.com.br/pay/ACDUG1SAJG', 'Kit', true),
  ('Kit lenhador + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/0ZBE2RWUG', 'Kit', true),
  ('Kit Lenhador + Pomada efeito úmido', 'https://seguro.loja-barbalenhador.com.br/pay/DJPR0HMVA', 'Kit', true),
  ('Kit Premium + Minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/ZD6KGHVU5W', 'Kit', true),
  ('Máquina de acabamento', 'https://seguro.loja-barbalenhador.com.br/pay/SWOZWUP6SW', 'Acessório', true);